[metadata]
name = sitejs
version = 1.0.0
author = Purrple-hub
description = SiteJS.py – the Python Small Web builder
long_description = file: README.md
long_description_content_type = text/markdown
license = Boost Software License 1.0
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    License :: OSI Approved :: Boost Software License 1.0

[options]
packages = find:
python_requires = >=3.9
install_requires =
    markdown>=3.5
    jinja2>=3.1
    watchdog>=3.0

[options.entry_points]
console_scripts =
    sitejs = sitejs:main
