#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const http = require('http');
const https = require('https');
const { spawn, exec } = require('child_process');
const readline = require('readline');

const VERSION = '1.0.0';
const DEFAULT_PORT = 4433;
const DEFAULT_HOST = '127.0.0.1';

const TEMPLATES = {
  'pages/index.md': `# Welcome to SiteJS

This site was created with SiteJS.py and the Node.js companion.

## Quick Start

Edit this file in \`pages/index.md\` and watch the magic happen.

### Features

- **Zero config** – just run \`sitejs serve\`
- **Live reload** – changes appear instantly
- **Markdown** – write content in plain text
- **Built-in database** – JSON storage via JSDB
- **Static export** – \`sitejs build\` for deployment

## Getting Started

1. Edit this file
2. Create new \`.md\` files in \`pages/\`
3. Add static assets to \`public/\`
4. Customize templates in \`templates/\`

Happy building! 🚀`,

  'templates/page.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title | default("SiteJS") }}</title>
    <link rel="stylesheet" href="/static/style.css">
    <script src="/static/reload.js" defer></script>
</head>
<body>
    <div class="container">
        <header>
            <h1>{{ title }}</h1>
            <nav>
                <a href="/">Home</a>
                <a href="/about">About</a>
                <a href="/blog">Blog</a>
            </nav>
        </header>
        <main>
            {{ content }}
        </main>
        <footer>
            <p>Generated by SiteJS.py</p>
        </footer>
    </div>
</body>
</html>`,

  'public/style.css': `* { margin:0; padding:0; box-sizing:border-box; }
body { font-family: system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif; background:#f8f9fa; color:#212529; line-height:1.6; padding:2rem 1rem; }
.container { max-width:960px; margin:0 auto; background:#fff; padding:2rem; border-radius:12px; box-shadow:0 4px 24px rgba(0,0,0,0.06); }
header { border-bottom:1px solid #e9ecef; padding-bottom:1rem; margin-bottom:2rem; }
header h1 { font-weight:600; font-size:2.2rem; letter-spacing:-0.02em; }
nav { margin-top:0.5rem; }
nav a { color:#0d6efd; text-decoration:none; margin-right:1.5rem; font-weight:500; }
nav a:hover { text-decoration:underline; }
main { min-height:60vh; }
h1, h2, h3, h4 { margin:1.5rem 0 0.75rem; font-weight:600; line-height:1.2; }
p { margin-bottom:1rem; }
a { color:#0d6efd; }
code { background:#f1f3f5; padding:0.2rem 0.4rem; border-radius:4px; font-size:0.9em; }
pre { background:#f1f3f5; padding:1rem; border-radius:8px; overflow-x:auto; }
ul, ol { padding-left:1.5rem; margin-bottom:1rem; }
blockquote { border-left:4px solid #0d6efd; padding-left:1rem; color:#6c757d; margin:1rem 0; }
table { width:100%; border-collapse:collapse; margin:1rem 0; }
th, td { border:1px solid #dee2e6; padding:0.5rem 0.75rem; text-align:left; }
th { background:#e9ecef; }
footer { border-top:1px solid #e9ecef; padding-top:1rem; margin-top:2rem; color:#6c757d; font-size:0.9rem; }
img { max-width:100%; height:auto; border-radius:6px; }
@media (max-width:600px) { body { padding:1rem; } .container { padding:1rem; } }`,

  'public/reload.js': `(function() {
    var version = 0;
    function check() {
        fetch('/__version')
            .then(function(r) { return r.text(); })
            .then(function(v) {
                var newVer = parseInt(v, 10);
                if (newVer > version) {
                    version = newVer;
                    location.reload();
                }
            })
            .catch(function() {});
    }
    setInterval(check, 500);
})();`,

  'data/db.json': '{}'
};

const DIRS = ['pages', 'public', 'templates', 'data', 'logs', 'dist'];

function ensureStructure() {
  for (const dir of DIRS) {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      console.log(`📁 Created: ${dir}/`);
    }
  }

  for (const [file, content] of Object.entries(TEMPLATES)) {
    if (!fs.existsSync(file)) {
      fs.writeFileSync(file, content, 'utf-8');
      console.log(`📄 Created: ${file}`);
    }
  }
}

function checkPython() {
  try {
    const result = exec('python3 --version', (err, stdout) => {
      if (err) {
        console.log('❌ Python 3 not found. Please install Python 3.9+');
        console.log('   https://www.python.org/downloads/');
        process.exit(1);
      }
      console.log(`✅ ${stdout.trim()}`);
    });
  } catch (e) {
    console.log('❌ Python 3 not found. Please install Python 3.9+');
    process.exit(1);
  }
}

function installPythonDeps() {
  console.log('📦 Installing Python dependencies...');
  const deps = ['markdown', 'jinja2', 'watchdog', 'cryptography'];
  exec(`pip3 install ${deps.join(' ')}`, (err, stdout, stderr) => {
    if (err) {
      console.log('⚠️  Failed to install Python deps. Run manually:');
      console.log(`   pip3 install ${deps.join(' ')}`);
    } else {
      console.log('✅ Python dependencies installed');
    }
  });
}

function checkSitePy() {
  const sitejsPath = path.join(__dirname, 'sitejs.py');
  if (!fs.existsSync(sitejsPath)) {
    console.log('❌ sitejs.py not found in current directory');
    console.log('   Please clone the repository or download sitejs.py');
    process.exit(1);
  }
  return sitejsPath;
}

function serve(port, host) {
  port = port || DEFAULT_PORT;
  host = host || DEFAULT_HOST;

  console.log(`🚀 Starting SiteJS.py server on http://${host}:${port}`);
  console.log(`   Press Ctrl+C to stop`);

  const python = process.platform === 'win32' ? 'python' : 'python3';
  const args = [checkSitePy(), 'serve', '--host', host, '--port', port];
  const proc = spawn(python, args, {
    stdio: 'inherit',
    cwd: process.cwd()
  });

  proc.on('error', (err) => {
    console.log('❌ Failed to start server:', err.message);
    process.exit(1);
  });

  proc.on('close', (code) => {
    if (code !== 0) {
      console.log(`❌ Server exited with code ${code}`);
    }
    process.exit(code);
  });

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: true
  });

  rl.on('SIGINT', () => {
    console.log('\n🛑 Stopping server...');
    proc.kill('SIGINT');
    rl.close();
  });

  return proc;
}

function build(outputDir) {
  outputDir = outputDir || 'dist';
  console.log(`🏗️  Building static site to ${outputDir}/`);

  const python = process.platform === 'win32' ? 'python' : 'python3';
  const args = [checkSitePy(), 'build', '--output', outputDir];
  const proc = spawn(python, args, {
    stdio: 'inherit',
    cwd: process.cwd()
  });

  proc.on('error', (err) => {
    console.log('❌ Build failed:', err.message);
    process.exit(1);
  });

  proc.on('close', (code) => {
    if (code !== 0) {
      console.log(`❌ Build failed with code ${code}`);
      process.exit(code);
    }
    console.log('✅ Build complete!');
  });
}

function deploy() {
  console.log('📤 Deploying site...');

  const python = process.platform === 'win32' ? 'python' : 'python3';
  const args = [checkSitePy(), 'deploy'];
  const proc = spawn(python, args, {
    stdio: 'inherit',
    cwd: process.cwd()
  });

  proc.on('error', (err) => {
    console.log('❌ Deploy failed:', err.message);
    process.exit(1);
  });

  proc.on('close', (code) => {
    if (code !== 0) {
      console.log(`❌ Deploy failed with code ${code}`);
      process.exit(code);
    }
    console.log('✅ Deploy complete!');
  });
}

function db(action, key, value) {
  const python = process.platform === 'win32' ? 'python' : 'python3';
  const args = [checkSitePy(), 'db', action];
  if (key) args.push(key);
  if (value) args.push(value);

  const proc = spawn(python, args, {
    stdio: 'inherit',
    cwd: process.cwd()
  });

  proc.on('error', (err) => {
    console.log('❌ Database command failed:', err.message);
    process.exit(1);
  });

  proc.on('close', (code) => {
    if (code !== 0) {
      process.exit(code);
    }
  });
}

function newSite(name) {
  if (!name) {
    console.log('❌ Please provide a site name');
    console.log('   Usage: sitejs-node new <name>');
    process.exit(1);
  }

  if (fs.existsSync(name)) {
    console.log(`❌ Directory "${name}" already exists`);
    process.exit(1);
  }

  fs.mkdirSync(name, { recursive: true });
  const cwd = process.cwd();
  process.chdir(name);

  ensureStructure();

  process.chdir(cwd);

  console.log(`✅ Created new site: ${name}`);
  console.log(`   cd ${name}`);
  console.log('   sitejs-node serve');
}

function generateSiteJsDocs() {
  const docs = `# SiteJS.py Node.js Companion

## Overview

**sitejs-node.js** is a lightweight Node.js wrapper that makes SiteJS.py instantly accessible to JavaScript developers. It provides a familiar Node.js CLI experience while leveraging the full power of Python-based SiteJS.py for content rendering, server operations, and site building.

## Why Use This?

- **Zero friction** – no need to learn Python to get started
- **Node.js CLI** – familiar commands for JavaScript developers
- **Automatic setup** – creates directory structure and installs deps
- **Bridge between worlds** – use Node.js tools alongside Python SSG power

## Installation

### Global Install

\`\`\`bash
npm install -g sitejs-node
\`\`\`

### Local Install

\`\`\`bash
npm install --save-dev sitejs-node
\`\`\`

### Direct Download

\`\`\`bash
curl -O https://raw.githubusercontent.com/Purrple-hub/SiteJS.py/main/sitejs-node.js
chmod +x sitejs-node.js
./sitejs-node.js --help
\`\`\`

## Requirements

- **Node.js** 16+ (for the wrapper)
- **Python** 3.9+ (for SiteJS.py)
- **pip** (to install Python dependencies)

The wrapper will automatically check for these and guide you through installation.

## Commands

### \`sitejs-node new <name>\`

Creates a new SiteJS.py project with all necessary directories and default files.

\`\`\`bash
sitejs-node new my-site
cd my-site
\`\`\`

**What it creates:**

\`\`\`
my-site/
├── pages/          # Markdown content
│   └── index.md
├── public/         # Static assets (CSS, JS, images)
│   ├── style.css
│   └── reload.js
├── templates/      # Jinja2 templates
│   └── page.html
├── data/           # JSON database
│   └── db.json
└── logs/           # Server logs
    └── sitejs.log
\`\`\`

### \`sitejs-node serve [--port PORT] [--host HOST]\`

Starts the development server with live reload.

\`\`\`bash
sitejs-node serve                # Default: http://127.0.0.1:4433
sitejs-node serve --port 8080    # Custom port
sitejs-node serve --host 0.0.0.0 # Bind to all interfaces
\`\`\`

**Features:**
- Automatic SSL (self-signed)
- Live reload on file changes
- Markdown → HTML rendering
- Jinja2 templating
- JSON database (JSDB)

### \`sitejs-node build [--output DIR]\`

Builds the entire site as static HTML for deployment.

\`\`\`bash
sitejs-node build                # Builds to ./dist
sitejs-node build --output docs  # Builds to ./docs
\`\`\`

### \`sitejs-node deploy\`

Deploys the built site to your configured target.

\`\`\`bash
sitejs-node deploy
\`\`\`

**Configure in \`sitejs.toml\`:**

\`\`\`toml
deploy_method = "rsync"
deploy_target = "user@server:/var/www/html"
\`\`\`

### \`sitejs-node db <action> [key] [value]\`

Manages the built-in JSDB database.

\`\`\`bash
sitejs-node db get mykey
sitejs-node db set mykey '{"hello": "world"}'
sitejs-node db delete mykey
sitejs-node db all
\`\`\`

## Examples

### Example 1: Quick Blog

\`\`\`bash
# Create site
sitejs-node new my-blog
cd my-blog

# Create a blog post
echo "# My First Post\n\nWelcome to my blog!" > pages/post-1.md

# Start server
sitejs-node serve
# Open http://127.0.0.1:4433/post-1
\`\`\`

### Example 2: Custom Template

Create \`templates/blog.html\`:

\`\`\`html
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
    <link rel="stylesheet" href="/static/style.css">
</head>
<body>
    <article>
        <h1>{{ title }}</h1>
        {{ content }}
    </article>
</body>
</html>
\`\`\`

Reference it in your Markdown frontmatter:

\`\`\`yaml
---
template: blog.html
---
# My Post
Content here...
\`\`\`

### Example 3: Using the Database

\`\`\`bash
# Store data
sitejs-node db set visitors '{"count": 42}'

# Query data
sitejs-node db get visitors
\`\`\`

## Integration with Node.js Projects

In a Node.js project, you can use this as a build script:

\`\`\`json
{
  "scripts": {
    "start": "sitejs-node serve",
    "build": "sitejs-node build",
    "deploy": "sitejs-node deploy"
  }
}
\`\`\`

Or as an npm package:

\`\`\`javascript
const sitejs = require('sitejs-node');

// Programmatic use coming soon!
// sitejs.serve({ port: 3000 });
// sitejs.build({ output: 'public' });
\`\`\`

## Troubleshooting

### "Python 3 not found"

Install Python from https://www.python.org/downloads/

### "sitejs.py not found"

Make sure you're in the SiteJS.py repository root, or clone it:

\`\`\`bash
git clone https://github.com/Purrple-hub/SiteJS.py.git
cd SiteJS.py
\`\`\`

### "Module not found: markdown"

Install Python dependencies:

\`\`\`bash
pip3 install markdown jinja2 watchdog cryptography
\`\`\`

Or let the wrapper do it automatically (it tries on first run).

## Comparison: SiteJS.py vs Site.js

| Feature | SiteJS.py | Site.js (Node) |
|---------|-----------|----------------|
| **Language** | Python | Node.js |
| **Status** | Active | Discontinued |
| **Zero config** | ✅ | ✅ |
| **Live reload** | ✅ | ✅ |
| **Markdown** | ✅ | ✅ (Hugo) |
| **JSDB** | ✅ (JSON) | ✅ (JSDB) |
| **SSL** | ✅ (self-signed) | ✅ |
| **Static export** | ✅ | ✅ |
| **Deployment** | ✅ (rsync, FTP, S3, SFTP) | ❌ (manual) |
| **Plugins** | ✅ | ❌ |
| **Small Web focus** | ✅ | ✅ |

## License

Boost Software License 1.0 – same as SiteJS.py.

## Contributing

1. Fork the repository
2. Create a feature branch
3. Submit a pull request

## Links

- **GitHub**: https://github.com/Purrple-hub/SiteJS.py
- **Documentation**: https://sitejs.readthedocs.io (coming soon)
- **Issues**: https://github.com/Purrple-hub/SiteJS.py/issues

---

**Start building your Small Web site today with SiteJS.py + Node.js companion!** 🚀
`;

  fs.writeFileSync('SiteJavaScript.MD', docs, 'utf-8');
  console.log('📄 Generated: SiteJavaScript.MD');
}

function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === '--help' || command === '-h') {
    console.log(`
SiteJS.py Node.js Companion v${VERSION}

Usage:
  sitejs-node new <name>          Create a new site
  sitejs-node serve [--port P] [--host H]  Start development server
  sitejs-node build [--output D]  Build static site
  sitejs-node deploy              Deploy to target
  sitejs-node db <action> [key] [value]  Manage database
  sitejs-node --help              Show this help
  sitejs-node --version           Show version

Examples:
  sitejs-node new my-site
  cd my-site
  sitejs-node serve --port 8080
  sitejs-node build
  sitejs-node deploy

For more information, see SiteJavaScript.MD
    `);
    process.exit(0);
  }

  if (command === '--version' || command === '-v') {
    console.log(`sitejs-node v${VERSION}`);
    process.exit(0);
  }

  if (command === 'new') {
    const name = args[1];
    newSite(name);
    return;
  }

  if (command === 'serve') {
    let port = DEFAULT_PORT;
    let host = DEFAULT_HOST;
    for (let i = 1; i < args.length; i++) {
      if (args[i] === '--port' && args[i + 1]) {
        port = parseInt(args[i + 1], 10);
        i++;
      } else if (args[i] === '--host' && args[i + 1]) {
        host = args[i + 1];
        i++;
      }
    }
    ensureStructure();
    checkPython();
    installPythonDeps();
    serve(port, host);
    return;
  }

  if (command === 'build') {
    let output = 'dist';
    for (let i = 1; i < args.length; i++) {
      if ((args[i] === '--output' || args[i] === '-o') && args[i + 1]) {
        output = args[i + 1];
        i++;
      }
    }
    ensureStructure();
    checkPython();
    build(output);
    return;
  }

  if (command === 'deploy') {
    ensureStructure();
    checkPython();
    deploy();
    return;
  }

  if (command === 'db') {
    const action = args[1];
    const key = args[2];
    const value = args[3];
    if (!action) {
      console.log('❌ Please specify a database action: get, set, delete, all');
      process.exit(1);
    }
    ensureStructure();
    checkPython();
    db(action, key, value);
    return;
  }

  if (command === 'docs') {
    generateSiteJsDocs();
    return;
  }

  console.log(`❌ Unknown command: ${command}`);
  console.log('   Run sitejs-node --help for available commands');
  process.exit(1);
}

if (require.main === module) {
  main();
}

module.exports = {
  VERSION,
  ensureStructure,
  serve,
  build,
  deploy,
  db,
  newSite
};
